//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InFormationOfResturant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int Restaurant_Id { get; set; }
        public string Restaurant_Name { get; set; }
        public string Restaurant_Address { get; set; }
        public string Cuisine_Type { get; set; }
        public string Contact_Number { get; set; }
        public string Operating_Hours { get; set; }
    }
}
