//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RestaurantID { get; set; }
        public string RestaurantName { get; set; }
        public string OrderDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string DeliveryAddress { get; set; }
        public string Status { get; set; }
    }
}
